[about]
professional = "I study software engineering at the University of Waterloo, and I'm currently interning at Nokia for firmware development."
personal = "In my free time I help teach my university's Judo club, and recently I've mostly been playing Dwarf Fortress and reading parts of Terry Pratchett's 'Discworld.'"
gpa = "3.8"

[favourite]
languages = ["C++", "Python", "JavaScript", "Java"]
frameworks = ["React", "Spring", "SQL", "Docker", "Flask", "AWS", "ROS"]
skills = ["CAD", "Soldering", "Circuit design"]